services:
  db:
    image: postgres:17
    container_name: stayhub-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: stayhub
      POSTGRES_PASSWORD: stayhub_password
      POSTGRES_DB: stayhub

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: