"""add listing search indexes

Revision ID: 947c3b69fa5a
Revises: 9b8a892118ef
Create Date: 2026-09-29 00:16:16.559136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947c3b69fa5a'
down_revision: Union[str, Sequence[str], None] = '9b8a892118ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_properties_created_at'), 'properties', ['created_at'], unique=False)
    op.create_index(op.f('ix_properties_location'), 'properties', ['location'], unique=False)
    op.create_index(op.f('ix_properties_price_per_night'), 'properties', ['price_per_night'], unique=False)
    op.create_index(op.f('ix_properties_rating'), 'properties', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_rating'), table_name='properties')
    op.drop_index(op.f('ix_properties_price_per_night'), table_name='properties')
    op.drop_index(op.f('ix_properties_location'), table_name='properties')
    op.drop_index(op.f('ix_properties_created_at'), table_name='properties')
    # ### end Alembic commands ###
